analysis.tf

terraform does not like Enhanced Networking of c5

terraform does not like Enhanced Networking of c5

---

analysis.tf

fixing internal IP

---

analysis.tf

Removing letsencrypt access

---

instances.tf

Add additional windows bastion

---

instances.tf

Update name tag of new bastion

Update name tag

---

iam.tf

Add ops config bucket to bastion iam policies

Add config-bucket resources to bastion iam policies

---

instances.tf

Add config bucket env var to bastions

Add config bucket env var to bastions

---

instances.tf

Add NFS ports to bastion security group

Add NFS ports to bastion security group

---

instances.tf

Correct protocol usage for security group ingress definitions

Correct protocol usage for security group ingress definitions

---

.drone.yml
ad_instance.tf
analysis.tf
data.tf
iam.tf
instances.tf
main.tf
output.tf
s3.tf
tests/ops_test.py
variable.tf
versions.tf
vpc.tf

What changes does this PR bring?
terraform 12 upgrade
What are the relevant tickets?
YEL-3182
Are tests included? (if applicable)
Infra is already plan and tested in TEST account
What if you don’t make a change?
terraform 12 has been out since 2 years ago. It has made change to HCL 2 and code support more functionalities with bug fixes.

terraform code upgraded to 0.12 with modified test cases

---

data.tf
instances.tf

Protect Win Bastions 1 & 2.
Remove Win Bastion 2016 (we're never going to go live with that).

Create a new Win Bastion 4 (based on my latest Win19 build).

---

data.tf

Latest Win Bastion AMI has more defensive code in userdata script.

Use latest Win Bastion AMI (#276)

---

data.tf

...for more reliable initialisation

Rearrange rename, join domain and restart

---

data.tf

- Add a restart after RDS installation - and a final restart

Use the latest Win Bastion 2019 AMI (#314)

---

instances.tf

- if required it will come from array

Remove Win Bastion 3

---

instances.tf
tests/ops_test.py
variable.tf

- just for Prod
- until it is removed from Prod

Re-add Win Bastion 1

---

data.tf

- Which will copy the region & locale script to the host

Use the latest Win Bastion AMI (#288)

---

data.tf

- Win Bastion 4 to use the Win AMI (#292)

Automated Domain joining

---

instances.tf
tests/ops_test.py
variable.tf

Deploy Win Bastion 2 as part of array

---

data.tf

- Add RDP shortcut for Tab Dep 3 Prod

Use the latest Win Bastion AMI (#297)

---

data.tf

Force Ansible to use pip 3.9

---

analysis.tf
data.tf

These changes remove old team members from the dqusers.yml file contained within each build and add Bhuvaneshwaran Chinnaswamy from the CIT Team to these builds.

Update httpd analysis AMI (#471) / Update Linux Bastion AMI (#310)
